In [1]:
import numpy as np
from methods import Jacobi, Seidal

iteration: 1, x_cur: [10  8  9], x_next: [1.1 0.9 0.3]
iteration: 2, x_cur: [1.1 0.9 0.3], x_next: [0.94 0.88 0.83]
iteration: 3, x_cur: [0.94 0.88 0.83], x_next: [0.995 0.811 0.818]
iteration: 4, x_cur: [0.995 0.811 0.818], x_next: [1.0007 0.8177 0.8373]
iteration: 5, x_cur: [1.0007 0.8177 0.8373], x_next: [1.00196 0.81634 0.83653]
[1.002019 0.816543 0.836928]
[1.   0.9  0.92]


In [3]:
A = np.array([
    [10, -1, 1],
    [1, 10, -1],
    [1, -2, 10]
])
b = np.array([10, 8, 9])

display(Jacobi(A, b, 1e-10).get_solution()[0])
display(Seidal(A, b, 1e-10).get_solution()[0])
display(np.linalg.tensorsolve(A, b))

iteration: 1, x_cur: [10  8  9], x_next: [1.1 0.9 0.3]
iteration: 2, x_cur: [1.1 0.9 0.3], x_next: [0.94 0.88 0.83]
iteration: 3, x_cur: [0.94 0.88 0.83], x_next: [0.995 0.811 0.818]
iteration: 4, x_cur: [0.995 0.811 0.818], x_next: [1.0007 0.8177 0.8373]
iteration: 5, x_cur: [1.0007 0.8177 0.8373], x_next: [1.00196 0.81634 0.83653]
iteration: 6, x_cur: [1.00196 0.81634 0.83653], x_next: [1.002019 0.816543 0.836928]
iteration: 7, x_cur: [1.002019 0.816543 0.836928], x_next: [1.0020385 0.8165091 0.8368933]
iteration: 8, x_cur: [1.0020385 0.8165091 0.8368933], x_next: [1.00203842 0.81651452 0.83690203]
iteration: 9, x_cur: [1.00203842 0.81651452 0.83690203], x_next: [1.00203875 0.81651364 0.83690094]
iteration: 10, x_cur: [1.00203875 0.81651364 0.83690094], x_next: [1.00203873 0.81651378 0.83690115]
iteration: 11, x_cur: [1.00203873 0.81651378 0.83690115], x_next: [1.00203874 0.81651376 0.83690112]
iteration: 12, x_cur: [1.00203874 0.81651376 0.83690112], x_next: [1.00203874 0.81651376 0

array([1.00203874, 0.81651376, 0.83690112])

array([1.  , 0.9 , 0.92])

array([0.98365679, 0.79775281, 0.96118488])