In [1]:
import numpy as np
from methods import Jacobi, Seidal

[0.98365679 0.79775281 0.96118488]
iteration: 1, x_cur: [10  8  9], x_next: [0.9 0.7 1.5]
iteration: 2, x_cur: [0.9 0.7 1.5], x_next: [0.92 0.86 0.95]
iteration: 3, x_cur: [0.92 0.86 0.95], x_next: [0.991 0.803 0.98 ]
iteration: 4, x_cur: [0.991 0.803 0.98 ], x_next: [0.9823 0.7989 0.9615]
iteration: 5, x_cur: [0.9823 0.7989 0.9615], x_next: [0.98374 0.79792 0.96155]
[0.983637 0.797781 0.96121 ]
[1.   0.7  0.94]


In [2]:
A = np.array([
    [10, -1, 1],
    [1, 10, -1],
    [1, -2, 10]
])
b = np.array([10, 8, 9])

display(Jacobi(A, b, 1e-3).get_solution()[0])
display(Seidal(A, b, 1e-3).get_solution()[0])
display(np.linalg.tensorsolve(A, b))

iteration: 1, x_cur: [10  8  9], x_next: [0.9 0.7 1.5]
iteration: 2, x_cur: [0.9 0.7 1.5], x_next: [0.92 0.86 0.95]
iteration: 3, x_cur: [0.92 0.86 0.95], x_next: [0.991 0.803 0.98 ]
iteration: 4, x_cur: [0.991 0.803 0.98 ], x_next: [0.9823 0.7989 0.9615]
iteration: 5, x_cur: [0.9823 0.7989 0.9615], x_next: [0.98374 0.79792 0.96155]


array([0.983637, 0.797781, 0.96121 ])

array([1.  , 0.7 , 0.94])

array([0.98365679, 0.79775281, 0.96118488])